from __future__ import annotations

from app.core.models import AgentDefinition, ArtifactType
from app.packs.base import ContextPolicy, EvalCheck, ReturnContract, SessionPolicy, WorkflowPack, WorkflowStep


CODE_RD_INSTITUTIONAL_PACK_NAME = "code_rd_institutional"


def get_code_rd_institutional_pack() -> WorkflowPack:
    return WorkflowPack(
        name=CODE_RD_INSTITUTIONAL_PACK_NAME,
        description=(
            "Institutional code R&D workflow with GPT as the trusted main thread, "
            "DeepSeek long-context review, executor branches, synthesis, and final approval."
        ),
        agents=[
            _agent(
                "context_reader",
                "ContextReader",
                "Read the request and available repository context, then produce a long-context brief, constraints, and risk notes for the GPT main thread.",
                ["read_file", "list_files", "search_files", "write_artifact"],
                "mock-institutional-context-reader",
            ),
            _agent(
                "planner",
                "Planner",
                "Act as the trusted GPT main thread: clarify the request and produce a concrete implementation plan from the context brief.",
                ["read_file", "list_files", "search_files", "write_artifact"],
                "mock-institutional-planner",
            ),
            _agent(
                "review_gate",
                "ReviewGate",
                "Use long-context review to challenge the GPT plan for feasibility, risks, missing acceptance criteria, and context drift before execution.",
                ["read_file", "search_files", "write_artifact"],
                "mock-institutional-reviewer",
            ),
            _agent(
                "dispatcher",
                "Dispatcher",
                "Act as the GPT main thread: respond to review feedback and translate the approved plan into executor work packages.",
                ["write_artifact"],
                "mock-institutional-coordinator",
            ),
            _agent(
                "implementation_executor",
                "ImplementationExecutor",
                "Act as the GPT code executor: prepare the implementation patch or changed-file summary.",
                ["read_file", "list_files", "search_files", "write_artifact"],
                "mock-institutional-builder",
            ),
            _agent(
                "test_executor",
                "TestExecutor",
                "Act as the GPT test executor: run or mock tests and report verification status with residual risk.",
                ["read_file", "run_test_command", "write_artifact"],
                "mock-institutional-builder",
            ),
            _agent(
                "context_reviewer",
                "ContextReviewer",
                "Use long-context review to compare the patch and test report against the original brief, repository constraints, and review feedback.",
                ["read_file", "search_files", "write_artifact"],
                "mock-institutional-context-reviewer",
            ),
            _agent(
                "synthesizer",
                "Synthesizer",
                "Act as the GPT main thread: merge executor outputs, answer DeepSeek review concerns, and identify unresolved risk.",
                ["write_artifact"],
                "mock-institutional-synthesizer",
            ),
            _agent(
                "final_reviewer",
                "FinalReviewer",
                "Perform a final long-context quality and risk review of the synthesized delivery for the GPT approver.",
                ["read_file", "search_files", "write_artifact"],
                "mock-institutional-reviewer",
            ),
            _agent(
                "final_approver",
                "FinalApprover",
                "Act as the trusted GPT main thread: make the final approval decision using the delivery summary and DeepSeek final review.",
                ["write_artifact"],
                "mock-institutional-final-approver",
            ),
        ],
        steps=[
            WorkflowStep(
                name="read_context",
                agent_role="ContextReader",
                required_inputs=["goal"],
                allowed_tools=["read_file", "list_files", "search_files", "write_artifact"],
                phase="context",
                context_policy=ContextPolicy(artifact_excerpt_chars=4000, max_artifacts=2, max_upstream_handoffs=2),
                produces_artifact_type=ArtifactType.SOURCE_SUMMARY.value,
                coordination_role="gate",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
            WorkflowStep(
                name="plan_delivery",
                agent_role="Planner",
                required_artifacts=[ArtifactType.SOURCE_SUMMARY.value],
                allowed_tools=["read_file", "list_files", "search_files", "write_artifact"],
                depends_on=["read_context"],
                phase="planning",
                context_policy=ContextPolicy(artifact_excerpt_chars=12000, max_artifacts=4, max_upstream_handoffs=4),
                produces_artifact_type=ArtifactType.DESIGN_DOC.value,
                coordination_role="controller",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
            WorkflowStep(
                name="review_plan",
                agent_role="ReviewGate",
                required_artifacts=[ArtifactType.SOURCE_SUMMARY.value, ArtifactType.DESIGN_DOC.value],
                allowed_tools=["read_file", "search_files", "write_artifact"],
                depends_on=["plan_delivery"],
                phase="review_gate",
                context_policy=ContextPolicy(artifact_excerpt_chars=20000, max_artifacts=5, max_upstream_handoffs=5),
                produces_artifact_type=ArtifactType.RESEARCH_NOTE.value,
                coordination_role="gate",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
            WorkflowStep(
                name="dispatch_work",
                agent_role="Dispatcher",
                required_artifacts=[
                    ArtifactType.SOURCE_SUMMARY.value,
                    ArtifactType.DESIGN_DOC.value,
                    ArtifactType.RESEARCH_NOTE.value,
                ],
                allowed_tools=["write_artifact"],
                depends_on=["review_plan"],
                phase="dispatch",
                context_policy=ContextPolicy(artifact_excerpt_chars=8000, max_artifacts=5, max_upstream_handoffs=5),
                produces_artifact_type=ArtifactType.RESEARCH_NOTE.value,
                coordination_role="controller",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
            WorkflowStep(
                name="prepare_patch",
                agent_role="ImplementationExecutor",
                required_artifacts=[ArtifactType.SOURCE_SUMMARY.value, ArtifactType.DESIGN_DOC.value, ArtifactType.RESEARCH_NOTE.value],
                allowed_tools=["read_file", "list_files", "search_files", "write_artifact"],
                depends_on=["dispatch_work"],
                phase="execution",
                context_policy=ContextPolicy(artifact_excerpt_chars=16000, max_artifacts=6, max_upstream_handoffs=4),
                produces_artifact_type=ArtifactType.PATCH.value,
                coordination_role="subagent",
                controller_step="dispatch_work",
                return_contract=ReturnContract(
                    required_artifact_types=[ArtifactType.PATCH.value],
                    require_risk_notes=True,
                ),
                runtime="acp",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                    requires_approval=True,
                ),
                ownership={
                    "artifacts": [ArtifactType.PATCH.value],
                    "workspaces": ["prepare_patch"],
                },
            ),
            WorkflowStep(
                name="test_changes",
                agent_role="TestExecutor",
                required_artifacts=[
                    ArtifactType.SOURCE_SUMMARY.value,
                    ArtifactType.DESIGN_DOC.value,
                    ArtifactType.RESEARCH_NOTE.value,
                    ArtifactType.PATCH.value,
                ],
                allowed_tools=["read_file", "run_test_command", "write_artifact"],
                depends_on=["prepare_patch"],
                phase="execution",
                context_policy=ContextPolicy(artifact_excerpt_chars=16000, max_artifacts=6, max_upstream_handoffs=4),
                produces_artifact_type=ArtifactType.TEST_REPORT.value,
                coordination_role="subagent",
                controller_step="dispatch_work",
                return_contract=ReturnContract(
                    required_artifact_types=[ArtifactType.TEST_REPORT.value],
                    require_risk_notes=True,
                ),
                runtime="acp",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                    requires_approval=True,
                ),
                requires_eval_pass=True,
                required_eval_checks=["patched_local_test_command"],
                ownership={
                    "artifacts": [ArtifactType.TEST_REPORT.value],
                    "workspaces": ["test_changes"],
                },
            ),
            WorkflowStep(
                name="review_context_alignment",
                agent_role="ContextReviewer",
                required_artifacts=[
                    ArtifactType.SOURCE_SUMMARY.value,
                    ArtifactType.DESIGN_DOC.value,
                    ArtifactType.RESEARCH_NOTE.value,
                    ArtifactType.PATCH.value,
                    ArtifactType.TEST_REPORT.value,
                ],
                allowed_tools=["read_file", "search_files", "write_artifact"],
                depends_on=["prepare_patch", "test_changes"],
                phase="context_review",
                context_policy=ContextPolicy(artifact_excerpt_chars=24000, max_artifacts=8, max_upstream_handoffs=6),
                produces_artifact_type=ArtifactType.RESEARCH_NOTE.value,
                coordination_role="gate",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
            WorkflowStep(
                name="synthesize_delivery",
                agent_role="Synthesizer",
                required_artifacts=[
                    ArtifactType.DESIGN_DOC.value,
                    ArtifactType.RESEARCH_NOTE.value,
                    ArtifactType.SOURCE_SUMMARY.value,
                    ArtifactType.PATCH.value,
                    ArtifactType.TEST_REPORT.value,
                ],
                allowed_tools=["write_artifact"],
                depends_on=["review_context_alignment"],
                phase="synthesis",
                context_policy=ContextPolicy(artifact_excerpt_chars=20000, max_artifacts=8, max_upstream_handoffs=6),
                produces_artifact_type=ArtifactType.FINAL_REPORT.value,
                coordination_role="synthesizer",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
            WorkflowStep(
                name="final_review",
                agent_role="FinalReviewer",
                required_artifacts=[
                    ArtifactType.SOURCE_SUMMARY.value,
                    ArtifactType.DESIGN_DOC.value,
                    ArtifactType.RESEARCH_NOTE.value,
                    ArtifactType.PATCH.value,
                    ArtifactType.TEST_REPORT.value,
                    ArtifactType.FINAL_REPORT.value,
                ],
                allowed_tools=["read_file", "search_files", "write_artifact"],
                depends_on=["synthesize_delivery"],
                phase="final_review",
                context_policy=ContextPolicy(artifact_excerpt_chars=24000, max_artifacts=8, max_upstream_handoffs=6),
                produces_artifact_type=ArtifactType.RESEARCH_NOTE.value,
                coordination_role="gate",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
            WorkflowStep(
                name="final_approval",
                agent_role="FinalApprover",
                required_artifacts=[ArtifactType.FINAL_REPORT.value, ArtifactType.RESEARCH_NOTE.value],
                allowed_tools=["write_artifact"],
                depends_on=["final_review"],
                phase="final_approval",
                context_policy=ContextPolicy(artifact_excerpt_chars=20000, max_artifacts=10, max_upstream_handoffs=8),
                produces_artifact_type=ArtifactType.FINAL_REPORT.value,
                coordination_role="controller",
                runtime="session",
                session_policy=SessionPolicy(
                    persistent=True,
                    resume_strategy="latest_artifact_and_trace",
                ),
            ),
        ],
        eval_checks=[
            EvalCheck(
                name="context_brief_exists",
                description="DeepSeek ContextReader must produce a long-context brief before GPT planning.",
                severity="blocker",
                required_artifact_types=[ArtifactType.SOURCE_SUMMARY.value],
            ),
            EvalCheck(
                name="plan_exists",
                description="GPT Planner must produce an implementation plan.",
                severity="blocker",
                required_artifact_types=[ArtifactType.DESIGN_DOC.value],
            ),
            EvalCheck(
                name="review_gate_exists",
                description="DeepSeek ReviewGate must produce a review note before GPT dispatch.",
                severity="blocker",
                required_artifact_types=[ArtifactType.RESEARCH_NOTE.value],
            ),
            EvalCheck(
                name="dispatch_summary_exists",
                description="GPT Dispatcher must produce executor work packages.",
                severity="blocker",
                required_artifact_types=[ArtifactType.RESEARCH_NOTE.value],
            ),
            EvalCheck(
                name="patch_summary_exists",
                description="GPT implementation executor must produce a patch summary.",
                severity="blocker",
                required_artifact_types=[ArtifactType.PATCH.value],
            ),
            EvalCheck(
                name="test_report_exists",
                description="GPT test executor must produce a test report.",
                severity="blocker",
                required_artifact_types=[ArtifactType.TEST_REPORT.value],
            ),
            EvalCheck(
                name="context_alignment_review_exists",
                description="DeepSeek ContextReviewer must produce an alignment review before synthesis.",
                severity="blocker",
                required_artifact_types=[ArtifactType.RESEARCH_NOTE.value],
            ),
            EvalCheck(
                name="synthesis_exists",
                description="GPT Synthesizer must produce the delivery report.",
                severity="blocker",
                required_artifact_types=[ArtifactType.FINAL_REPORT.value],
            ),
            EvalCheck(
                name="final_approval_exists",
                description="GPT FinalApprover must produce the final approved delivery artifact.",
                severity="blocker",
                required_artifact_types=[ArtifactType.FINAL_REPORT.value],
            ),
        ],
        final_artifact_type=ArtifactType.FINAL_REPORT.value,
    )


def _agent(
    suffix: str,
    role: str,
    system_prompt: str,
    tool_permissions: list[str],
    model: str,
) -> AgentDefinition:
    return AgentDefinition(
        id=f"{CODE_RD_INSTITUTIONAL_PACK_NAME}-{suffix}",
        pack_name=CODE_RD_INSTITUTIONAL_PACK_NAME,
        role=role,
        system_prompt=system_prompt,
        model_config={"provider": "mock", "model": model},
        tool_permissions=tool_permissions,
        runtime_limits={"max_steps": 1},
    )
